Implémentation des Users, de quelques Rôles et Restrictions + home page et navbar
Prefabloc/symfony_forms pull request #10
Opened 2024-05-07 13:21 UTC by Vraendil

2024-05-13 05:30 UTC, Prefabloc commented
### Identification Prestation
- [ ] Avoir un rôle "Accueil", n'ayant accès qu'au formulaire d'identification (CRUD) , pas de navigation, pas de retour en arrière
  
### USER ROLES | Formulaires de Productions / Saisies
- [ ] La page "Home" affiche une page listant les formulaires auquel le collaborateur à accès ( exemple ROLE_PREFABLOC à accès a tous les formulaires Prefabloc, listé sur la page etc.

- Notes : Je n'avais pas vu que lors de la suppression des fichier TWIG les formulaires de production associé n'ont pas été changé, je le ferais, occupe toi juste d'avoir la possibilité de cliquer vers le lien du formulaire)

### Interface Utilisateur
- [ ] Navbar : Le menu en burger fonctionne (actuellement rien ne se passe quand je clique)
- [ ] Navbar : Les boutons [Home] [About] [Services] ne sont pas nécessaire
- [ ] Identification Prestation : L'UI doit s'adapter au mieux aux mobiles, écran pc, tablettes ( Responsive )




- Pour la partie YouSign je te fais confiance je n'ai pas pu tester, je n'ai pas la variable d'environnement YOUSIGN_SANDBOX_API_KEY

2024-05-13 05:34 UTC, Prefabloc requested changes

2024-05-13 05:34 UTC, Prefabloc commented on templates/identification_prestation/index.html.twig
Fichier inutile

2024-05-13 05:34 UTC, Prefabloc commented on templates/includes/navbar.html.twig
Verifier le menu une fois sur petit écran

2024-05-15 04:54 UTC, Prefabloc requested changes

2024-05-15 04:54 UTC, Prefabloc commented on config/packages/security.yaml
> +        ROLE_USER :
Le role Accueil est un rôle special,  un user ne peut pas se rendre sur les pages d'une personne "accueil"

2024-05-15 04:54 UTC, Prefabloc commented on src/Service/AccessDeniedListener.php
> +        if ( $exception instanceof AccessDeniedHttpException ) {
Tu peux m'éclairer.
C'est une redirection en cas de mauvais rôle vers une clé présente dans routes.yaml c'est ça

2024-05-15 04:54 UTC, Prefabloc commented on config/packages/security.yaml
> +        - { path: ^/logout , roles : ROLE_ACCUEIL }
Pourquoi ROLE_ACCUEIL

2024-05-15 04:54 UTC, Prefabloc commented on src/Controller/RegistrationController.php
> +            if ( $checkboxValue === 'on' && $checkboxValue != null ) {
checkboxValue ne peut pas être à la fois "on" et "null" donc la deuxième condition est inutile

2024-05-15 04:54 UTC, Prefabloc commented on src/Controller/RegistrationController.php
> +                        $user->setRoles(["ROLE_PREFABLOC" , "ROLE_USER"]);
si ROLE_PREFABLOC dans le role hierarchy possède déjà le role ROLE_USER, pas la peine de l'insérer une deuxième fois il me semble

2024-05-15 05:30 UTC, Prefabloc commented
Il manque des formulaires sur les pages d'accueil: exemple btpvalromex

2024-05-15 06:10 UTC, Vraendil commented on src/Controller/RegistrationController.php
> +            if ( $checkboxValue === 'on' && $checkboxValue != null ) {
corrigé

2024-05-15 06:16 UTC, Vraendil commented on config/packages/security.yaml
> +        - { path: ^/logout , roles : ROLE_ACCUEIL }
Parce que si je mets le rôle accueil héritant de user, je ne peux plus empêcher toutes les personnes qui sont en accueil d'accéder aux pages qui sont destinées aux employés qui renseignent les formulaire. Et vu que l'affichage des formulaires est factorisé sur une seule page (  '/' ) selon l'entreprise à laquelle appartient l'employé, dans ma logique le gars qui est juste au rôle accueil ne doit pas pouvoir s'y rendre. 
Et le /logout fallait juste préciser l'autorisation du coup vu que Role accueil n'hérite pas de user.

2024-05-15 06:17 UTC, Vraendil commented on src/Service/AccessDeniedListener.php
> +        if ( $exception instanceof AccessDeniedHttpException ) {
Oui je cherchais comment personnaliser la route de redirection en fonction du rôle choisi, et j'ai trouvé cette méthode sur internet ! Je voulais que la redirection roleaccueil soit différente des autres ( identification prestation )

2024-05-15 06:46 UTC, Vraendil commented on config/packages/security.yaml
> +        ROLE_USER :
Corrigé

2024-05-15 07:49 UTC, Prefabloc approved these changes

2024-05-15 07:53 UTC, Prefabloc approved these changes

2024-05-15 07:54 UTC, merged