Valromex
Prefabloc/symfony_forms pull request #2
Opened 2024-04-30 12:18 UTC by Vraendil

Pull Request de la branche Valromex

2024-05-06 09:00 UTC, Prefabloc requested changes

2024-05-06 09:00 UTC, Prefabloc commented on src/Controller/BTPValromexController.php
> +    public function btpValromexSaisieProduction(Request $request , EntityManagerInterface $entityManager ) : Response
Pareil,  A voir si possible de l'afficher dans une modale

2024-05-06 09:15 UTC, Vraendil commented on src/Controller/PrefablocController.php
> +    #[Route('/prefabloc/saisie/production' , name : 'app_prefacbloc_saisie_production')]
Pas de soucis pour les modals, on voit ça quand vous voulez en appel ! 

Et la première route c'est juste prefabloc/production 

La mienne c'est prefabloc/saisie/production

2024-05-07 04:57 UTC, Prefabloc approved these changes
A tester

2024-05-07 04:58 UTC, merged